AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Selecione a VPC
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Selecione a Subnet(s) da VPC escolhida
  ResourcePrefix:
    Type: String
    Description: Prefixo para padronizar os nomes dos recursos
    Default: AlchemBook
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: O nome do Key Pair a ser usado nas instancias EC2
  ASGMinCapacity:
    Type: Number
    Default: 0
  ASGMaxCapacity:
    Type: Number
    Default: 3
  ASGDesireedCapacity:
    Type: Number
    Default: 0
  DomainName:
    Type: String
    Description: Nome do dominio para o qual o DNS sera configurado
    Default: alchembook-workspace.lcdevops.click

Resources:
  # Bucket S3
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ResourcePrefix}-bucket

  # IAM Role para instancias
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ResourcePrefix}-InstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: !Sub arn:aws:s3:::${S3Bucket}/*
        - PolicyName: !Sub ${ResourcePrefix}-InstancePolicy2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - route53:ListHostedZones
                  - route53:ListResourceRecordSets
                  - route53:ChangeResourceRecordSets
                Resource: '*'

  # Launch Template (Descomentado)
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${ResourcePrefix}-LaunchTemplate
      VersionDescription: v1
      LaunchTemplateData:
        InstanceType: t3a.medium
        ImageId: ami-075686beab831bb7f # Exemplo de AMI publica (Ubuntu)
        UserData: !Base64
          Fn::Sub:
            - |
              #!/bin/bash

              # UserData script is located in /var/lib/cloud/instance/scripts/part-001

              # INITIAL CONFIGURATION
              apt update -y
              apt install -y s3fs zip unzip

              # INSTALL AWS CLI
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install

              # S3FS CONFIGURATION
              mkdir -p /tmp/${PROJECT_NAME}
              chown -R ubuntu:ubuntu /tmp/${PROJECT_NAME}
              echo "${S3BUCKET} /tmp/${PROJECT_NAME} fuse.s3fs _netdev,allow_other,iam_role=auto,url=https://s3.amazonaws.com 0 0" >> /etc/fstab
              systemctl daemon-reexec
              mount -a

              # BASHRC CONFIGURATION
              cp /tmp/${PROJECT_NAME}/bashrc-completion /tmp/bashrc-completion
              echo "" >> /tmp/bashrc-completion
              echo "export S3FS_DIR=/tmp/${PROJECT_NAME}" >> /tmp/bashrc-completion
              echo "" >> /tmp/bashrc-completion
              echo "PATH=\$PATH:/home/ubuntu/mylib" >> /tmp/bashrc-completion
              cat /tmp/bashrc-completion >> /home/ubuntu/.bashrc
              rm -rf /tmp/bashrc-completion

              # DOCKER CONFIGURATION
              cp /tmp/${PROJECT_NAME}/docker-config.sh /tmp/docker-config.sh
              chmod +x /tmp/docker-config.sh
              /tmp/docker-config.sh
              rm -rf /tmp/docker-config.sh

              # NODEJS CONFIGURATION
              runuser -l ubuntu -c 'cp /tmp/${PROJECT_NAME}/node-config.sh /tmp/node-config.sh'
              runuser -l ubuntu -c 'chmod +x /tmp/node-config.sh'
              runuser -l ubuntu -c '/tmp/node-config.sh'
              runuser -l ubuntu -c 'rm -rf /tmp/node-config.sh'
              runuser -l ubuntu -c 'nvm install 20'
              runuser -l ubuntu -c 'nvm use 20'
              runuser -l ubuntu -c 'npm install -g yarn'

              # ADD SSH KEY
              cp /tmp/${PROJECT_NAME}/id_ed25519 /home/ubuntu/.ssh/id_ed25519
              chmod 400 /home/ubuntu/.ssh/id_ed25519
              chown ubuntu:ubuntu /home/ubuntu/.ssh/id_ed25519

              # COMMANDS LIBRARY CONFIGURATION
              mkdir -p /home/ubuntu/mylib
              cp /tmp/${PROJECT_NAME}/gcp /home/ubuntu/mylib/gcp
              cp /tmp/${PROJECT_NAME}/env_* /home/ubuntu/mylib/.
              cp /tmp/${PROJECT_NAME}/my_commands /home/ubuntu/mylib/.
              cp /tmp/${PROJECT_NAME}/alchem_clone /home/ubuntu/mylib/.
              cp /tmp/${PROJECT_NAME}/ssh-config /home/ubuntu/mylib/.
              cp /tmp/${PROJECT_NAME}/docker_config /home/ubuntu/mylib/.
              chmod -R +x /home/ubuntu/mylib/.
              chown -R ubuntu:ubuntu /home/ubuntu/mylib/.

              # CONFIGURE DNS TO THE INSTANCE
              cp /tmp/${PROJECT_NAME}/dns-config.sh /tmp/dns-config.sh
              chmod +x /tmp/dns-config.sh
              /tmp/dns-config.sh ${DOMAIN_NAME}
            - S3BUCKET: !Ref S3Bucket
              PROJECT_NAME: !Ref ResourcePrefix
              DOMAIN_NAME: !Ref DomainName
        KeyName: !Ref KeyPair
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn

  # AutoScaling Group (Descomentado)
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds # Passa todas as subnets selecionadas
      MinSize: !Ref ASGMinCapacity
      MaxSize: !Ref ASGMaxCapacity
      DesiredCapacity: !Ref ASGDesireedCapacity
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: capacity-optimized
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt LaunchTemplate.LatestVersionNumber # Referência para a versao mais recente do LaunchTemplate

Outputs:
  S3BucketName:
    Description: Nome do S3 criado
    Value: !Ref S3Bucket