version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dev-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/psql:/var/lib/postgresql/data
    networks:
      - dev-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dev-net
  
  backend:
    build:
      context: /home/ubuntu/alchembook-backend
      dockerfile: /home/ubuntu/alchembook-infra/docker/node.Dockerfile
    container_name: alchembook-backend
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - dev-net

networks:
  dev-net:
